#!/bin/sh
# djvujpgpack v0.1 - script for pack jpeg files in one directory to djvu file
# Author: Kurashov Artem
# License: GNU GPLv3
# Depends: coreutils, dash, util-linux, djvulibre-bin, graphicsmagick
CURDIR=$(pwd)
flgloss=0
DECIBELVALUE=48
DPI=72
flgusage=0
while getopts ":b:d:lh" opt
do
    case $opt in
        b) DECIBELVALUE="$OPTARG"
            ;;
        d) DPI="$OPTARG"
            ;;
        l) flgloss=1
            ;;
        h) flgusage=1
            ;;
        *) echo "Unknown option -$OPTARG"
            exit 1
            ;;
    esac
done
shift "$(($OPTIND - 1))"
SRCS="$1"
DEST="$2"
if [ -z "$SRCS" -o -z "$DEST" -o $flgusage -eq 1 ]
then
    echo "usage: djvujpgpack [options] /path/to/dir/with/jpegs name-new-file.djvu"
    echo "options:"
    echo "    -b N    DECIBEL VALUE, default=48"
    echo "    -d N    DPI VALUE, default=72"
    echo "    -l      LOSSLESS, default=LOSSY"
    exit
fi
cd "$SRCS"
if [ "$(ls *.JPG 2> /dev/null)" != "" ]
then
    rename .JPG .jpg *.JPG
fi
while [ "$(ls *\ * 2> /dev/null)" != ""  ]
do
    rename \  _ *
done
if [ $flgloss -eq 0 ]
then
    for jpgfile in $(ls -1 *.jpg)
    do
        c44 -dpi "$DPI" -decibel "$DECIBELVALUE" $jpgfile $jpgfile.djvu
    done
else
    for jpgfile in $(ls -1 *.jpg)
    do
        jpgwidth=$(gm identify -format %w $jpgfile)
        jpgheight=$(gm identify -format %h $jpgfile)
        djvumake $jpgfile.djvu INFO="$jpgwidth","$jpgheight","$DPI" BGjp=$jpgfile
    done
fi
djvm -c "$CURDIR/$DEST" *.djvu && rm *.djvu
cd $CURDIR
